appName: cartservice
appNamespace: "${namespace}"
replicaCount: 1
imageName: gcr.io/google-samples/microservices-demo/cartservice
imageVersion: v0.5.0
containerVariables:
 - name: PORT
   value: "7070"
 - name: REDIS_ADDR
   value: "redis-svc:6379"
    
serviceName: cartservice
servicePort: 7070
serviceTargetPort: 7070
serviceType: ClusterIP

cpuRequest: 256m
memoryRequest: 400Mi
cpuLimit: 512m
memoryLimit: 600Mi