appName: frontend
appNamespace: "${namespace}"
replicaCount: 1
imageName: gcr.io/google-samples/microservices-demo/frontend
imageVersion: v0.5.0
containerVariables:
 - name: PORT
   value: "8080"
 - name: SHIPPING_SERVICE_ADDR
   value: "shippingservice:50051"
 - name: PRODUCT_CATALOG_SERVICE_ADDR
   value: "productcatalogservice:3550"
 - name: CART_SERVICE_ADDR
   value: "cartservice:7070"
 - name: CURRENCY_SERVICE_ADDR
   value: "currencyservice:7000"
 - name: AD_SERVICE_ADDR
   value: "adservice:9555"
 - name: CHECKOUT_SERVICE_ADDR
   value: "checkoutservice:5050"
 - name: RECOMMENDATION_SERVICE_ADDR
   value: "recommendationservice:8080"
    
serviceName: frontend
servicePort: 8080
serviceTargetPort: 8080
serviceType: NodePort

cpuRequest: 256m
memoryRequest: 400Mi
cpuLimit: 512m
memoryLimit: 600Mi