apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.appNamespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - image: "{{ .Values.imageName }}:{{ .Values.imageVersion }}"
        name: {{ .Values.appName }}
        resources:
         requests:
          cpu: {{ .Values.cpuRequest }}
          memory: {{ .Values.memoryRequest }}
         limits:
          cpu: {{ .Values.cpuLimit }}
          memory: {{ .Values.memoryLimit }}
        env:
        {{- range .Values.containerVariables }}
         - name: {{ .name }}
           value: {{ .value | quote }}
        {{- end }}
